"""Browser checks for the company pages (docs/notes/company-spec.md §0.10 / §9: 3, 9, 10, 13, 15, 16, /new).

Runs against a HELD isolated stack (`PAW_E2E_HOLD=1 node scripts/e2e-company.ts` prints `HOLD <url>`),
after its API checks created company `test-co` with agents alpha (lead) and beta.
Asserts COMPUTED STYLE / geometry, never class flags (the taskspad `[hidden]` lesson), and saves screenshots.

    /opt/homebrew/opt/python@3.10/bin/python3.10 scripts/e2e-company-ui.py <base-url> <screenshot-dir>
"""
import os
import re
import time
import sys

from playwright.sync_api import sync_playwright

BASE, OUT = sys.argv[1].rstrip("/"), sys.argv[2]
fails = 0


def ok(label, cond, detail=""):
    global fails
    print(("✓ " if cond else "✗ ") + label + (f" — {detail}" if detail else ""))
    if not cond:
        fails += 1


def display(page, sel):
    return page.evaluate("s => { const e = document.querySelector(s); return e ? getComputedStyle(e).display : 'missing' }", sel)


def rect(page, sel):
    return page.evaluate("s => { const e = document.querySelector(s); if (!e) return null; const r = e.getBoundingClientRect(); return {x:r.x, y:r.y, w:r.width, h:r.height} }", sel)


with sync_playwright() as p:
    # 1.29 ships no browser here; the system Chrome works over the same protocol
    b = p.chromium.launch(channel=os.environ.get("PW_CHANNEL", "chrome"))
    for scheme in ("light", "dark"):
        ctx = b.new_context(viewport={"width": 1440, "height": 900}, color_scheme=scheme)
        page = ctx.new_page()
        bad, errors = [], []
        page.on("response", lambda r: bad.append(f"{r.status} {r.url}") if r.status >= 400 and "/api/pr/" not in r.url else None)
        page.on("pageerror", lambda e: errors.append(str(e)))
        page.goto(f"{BASE}/company/test-co")
        page.wait_for_selector(".co-col:not(.co-loading) .co-workhead", timeout=30000)
        page.wait_for_timeout(2500)
        ok(f"[{scheme}] 3 /company/test-co loads with no 4xx (absolute /app.js)", not bad, "; ".join(bad))
        ok(f"[{scheme}] no page errors", not errors, "; ".join(errors))
        ok(f"[{scheme}] 10 #company is PAINTED (computed display)", display(page, "#company") != "none")
        team = page.inner_text(".co-team")
        ok(f"[{scheme}] 3 team line: alpha ★ and beta", "alpha ★" in team and "beta" in team, team)
        ok(f"[{scheme}] 10 CLIENT_BUILD stamp visible", page.is_visible(".co-build") and "build company-" in page.inner_text(".co-build"))
        ok(f"[{scheme}] SCOPED: the global sidebar and top filter bar are NOT painted", display(page, ".side") == "none" and display(page, ".top") == "none" and display(page, ".grip") == "none")
        ok(f"[{scheme}] the company page spans the full width", rect(page, "#company")["x"] == 0, str(rect(page, "#company")))
        hb = page.evaluate("getComputedStyle(document.getElementById('cohead')).backgroundColor")
        ok(f"[{scheme}] the slim header is painted, '← paw' + the company, no aubergine", display(page, "#cohead") == "flex" and "← paw" in page.inner_text("#cohead") and "Test Co" in page.inner_text("#cohead") and hb not in ("rgb(63, 14, 64)", "rgb(25, 23, 29)"), hb)
        if scheme == "light":
            # 13: the lead chat is paw's real conversation, in the right 400px at ≥1100px
            msgs, comp, co = rect(page, ".main > .msgs"), rect(page, ".main > .comp"), rect(page, "#company")
            ok("13 lead chat: the real #msgs + composer sit in a right column beside the company page", display(page, ".main > .msgs") != "none" and display(page, ".main > .comp") != "none" and msgs["x"] >= co["x"] + co["w"] - 2 and abs(msgs["w"] - 400) < 2, f"msgs={msgs} co={co}")
            ok("13 the chat header names the lead", page.inner_text("#title") == "alpha", page.inner_text("#title"))
            ok("13 the lead's PONG reply renders in that chat", re.search("pong", page.inner_text(".main > .msgs"), re.I) is not None)
            # the agents are REAL and may close beads themselves — compare against what the API says now
            ms_row = page.inner_text(".co-ms-row")
            api_ms = page.evaluate("""async () => { const d = await (await fetch('/api/company/test-co?fresh=1')).json();
              const m = await import('/company-model.js'); const r = m.milestones(d.issues, d.company.epic).find((x) => x.title === 'Milestone one');
              return r ? `${r.done}/${r.total}` : null }""")
            ok("13 the milestone row shows the API's done/total", api_ms is not None and api_ms in ms_row, f"{ms_row!r} vs {api_ms}")
            page.screenshot(path=f"{OUT}/company-home-light.png")
            # stale-while-revalidate. The delay lives IN the page (a fetch wrapper switched by a
            # sessionStorage flag) — a sync playwright route handler that sleeps blocks the test thread too.
            page.add_init_script("""(() => { const f = window.fetch; window.fetch = (u, o) => {
              const p = f(u, o); if (sessionStorage.getItem('slowco') && String(u).includes('/api/company/test-co'))
                return p.then((r) => new Promise((res) => setTimeout(() => res(r), 3000))); return p; }; })()""")
            def slow_on():
                page.evaluate("sessionStorage.setItem('slowco', '1')")
            def slow_off():
                page.evaluate("sessionStorage.removeItem('slowco')")
            slow_on()
            page.reload()
            page.wait_for_timeout(800)
            ok("SWR: with the API slow, the cached company paints at once, marked 'updating…'", "Test Co" in page.inner_text("#company") and "updating" in page.inner_text("#cohead"), page.inner_text("#cohead"))
            ok("the lead chat never shows the '~co' sentinel", "~co" not in page.inner_text(".main"), page.inner_text("#title"))
            page.wait_for_timeout(4000)
            ok("SWR: the fresh payload replaces it and the mark goes", "updating" not in page.inner_text("#cohead"))
            slow_off()
            page.route("**/api/company/test-co*", lambda route: route.fulfill(status=502, content_type="application/json", body='{"error":"bd: boom"}'))
            page.reload()
            page.wait_for_timeout(1500)
            ok("SWR: a FAILED refresh says so — the copy is never passed off as current", "couldn't refresh" in page.inner_text("#cohead") and "Test Co" in page.inner_text("#company"), page.inner_text("#cohead"))
            page.unroute("**/api/company/test-co*")
            page.evaluate("localStorage.clear()")
            slow_on()
            page.reload()
            page.wait_for_timeout(800)
            ok("cold (no cache): no '~co' anywhere while the lead is unknown", "~co" not in page.inner_text(".main"), page.inner_text("#title"))
            ok("cold (no cache): a skeleton, never a blank page — placeholders painted + 'loading…'", page.locator("#company .co-skel").count() >= 3 and display(page, "#company .co-skel") != "none" and "loading" in page.inner_text("#company"))
            ok("cold: the chat column never says 'no messages yet' before the lead is known", "no messages yet" not in page.inner_text(".main > .msgs"), page.inner_text(".main > .msgs")[:80])
            page.wait_for_timeout(4000)
            page.evaluate("localStorage.removeItem(Object.keys(localStorage).find(k => k.endsWith('.test-co.cache')))")  # keep only the company LIST copy
            page.reload()
            page.wait_for_timeout(800)
            ok("with only the company list cached, the chat column is the LEAD's from the first frame", page.inner_text("#title") == "alpha" and "Test Co" in page.inner_text("#company"), page.inner_text("#title"))
            slow_off()
            page.reload()
            page.wait_for_selector(".co-col:not(.co-loading) .co-workhead", timeout=30000)
            page.wait_for_timeout(1500)
            # the view toggle
            heads = page.eval_on_selector_all(".co-work .co-group h2", "els => els.map(e => e.textContent.trim())")
            ok("By agent (default): the lead first, then beta — the operator's beads live in the You block, not repeated", len(heads) >= 2 and heads[0].startswith("alpha") and heads[1].startswith("beta") and not any(h.startswith("You") for h in heads), str(heads))
            page.click('.co-views [data-view="status"]')
            page.wait_for_timeout(300)
            sheads = page.eval_on_selector_all(".co-work .co-group h2", "els => els.map(e => e.textContent.trim())")
            ok("By status groups by status", all(re.match(r"^(In progress|Blocked|To do|Done)", h) for h in sheads) and len(sheads) > 0, str(sheads))
            page.screenshot(path=f"{OUT}/company-bystatus-light.png")
            page.reload()
            page.wait_for_selector(".co-col:not(.co-loading) .co-workhead", timeout=30000)
            ok("the view choice persists per company (localStorage)", page.get_attribute('.co-views [data-view="status"]', "aria-pressed") == "true")
            page.goto(f"{BASE}/company/test-co?view=agent")
            page.wait_for_selector(".co-col:not(.co-loading) .co-workhead", timeout=30000)
            ok("?view=agent overrides the stored choice", page.get_attribute('.co-views [data-view="agent"]', "aria-pressed") == "true")
            # the bead MODAL + a comment
            ok("10 the bead modal is NOT painted before a bead is opened", display(page, "#comodal") == "none")
            if page.locator(".co-work .co-bead .co-t").count() == 0:
                page.click(".co-work .co-fold")  # the agents may have finished everything — open a done fold
                page.wait_for_timeout(300)
            cols_before = page.evaluate("[document.querySelector('.co-col').getBoundingClientRect().width, document.querySelector('.main > .msgs').getBoundingClientRect().x]")
            row_id = page.get_attribute(".co-work .co-bead", "data-open")
            page.click(".co-work .co-bead .co-t")
            page.wait_for_timeout(1500)
            ok("10 clicking a bead PAINTS the modal, centred, over a backdrop", display(page, "#comodal") == "flex" and display(page, ".co-backdrop") != "none" and page.evaluate("getComputedStyle(document.querySelector('.co-modal')).position") == "relative")
            m = rect(page, ".co-modal")
            ok("the modal is centred and at most 720px wide", m["w"] <= 721 and abs((m["x"] + m["w"] / 2) - 720) < 4, str(m))
            cols_after = page.evaluate("[document.querySelector('.co-col').getBoundingClientRect().width, document.querySelector('.main > .msgs').getBoundingClientRect().x]")
            ok("nothing behind it reflows: the list keeps its width, the lead chat column stays put", cols_before == cols_after, f"{cols_before} → {cols_after}")
            hb = page.evaluate("getComputedStyle(document.querySelector('.co-mhead')).backgroundColor")
            ok("the modal header is OPAQUE (its own background)", hb not in ("rgba(0, 0, 0, 0)", "transparent"), hb)
            ok("focus is inside the modal", page.evaluate("document.querySelector('.co-modal').contains(document.activeElement)"))
            for _ in range(8):
                page.keyboard.press("Tab")
            ok("Tab is trapped inside the modal", page.evaluate("document.querySelector('.co-modal').contains(document.activeElement)"))
            btn = page.evaluate("(() => { const b = document.querySelector('[data-act=comment]'); const cs = getComputedStyle(b); return [cs.color, cs.backgroundColor] })()")
            ok("the Comment button's label is readable (text colour != fill)", btn[0] != btn[1], str(btn))
            ok("the modal deep-links ?bead=", "bead=" in page.url, page.url)
            page.fill('[data-input="comment"]', "a comment from the browser check")
            page.focus('[data-input="comment"]')
            page.keyboard.press("Shift+Enter")
            ok("Shift+Enter is a newline, not a send", page.input_value('[data-input="comment"]').endswith("\n") and not page.is_disabled('[data-input="comment"]'))
            page.keyboard.press("Enter")
            page.wait_for_timeout(150)
            ok("Enter sends: box + button disabled, 'sending…'", page.is_disabled('[data-input="comment"]') and page.is_disabled('[data-act="comment"]') and "sending" in page.inner_text('[data-act="comment"]'))
            page.wait_for_function("() => !document.querySelector('[data-input=comment]').disabled", timeout=60000)
            ok("re-enabled only once the new comment is IN the rendered thread, box emptied", "a comment from the browser check" in page.inner_text(".co-mbody") and page.input_value('[data-input="comment"]') == "")
            page.screenshot(path=f"{OUT}/company-modal-light.png")
            page.keyboard.press("Escape")
            page.wait_for_timeout(600)
            ok("Esc closes the modal and stays on the company page", display(page, "#comodal") == "none" and page.url.endswith("/company/test-co"), page.url)
            ok("focus returns to the row that opened it", page.evaluate("document.activeElement?.dataset?.open") == row_id, str(page.evaluate("document.activeElement?.outerHTML?.slice(0,80)")))
            page.click(".co-work .co-bead .co-t")
            page.wait_for_timeout(800)
            page.click(".co-backdrop", position={"x": 5, "y": 5})
            page.wait_for_timeout(600)
            ok("a backdrop click closes it", display(page, "#comodal") == "none")
            page.click(".co-work .co-bead .co-t")
            page.wait_for_timeout(800)
            page.go_back()
            page.wait_for_timeout(1000)
            ok("Back closes it (and stays on the page)", display(page, "#comodal") == "none" and page.url.endswith("/company/test-co"), page.url)
            page.goto(f"{BASE}/company/test-co?bead={row_id}")
            page.wait_for_timeout(3000)
            ok("?bead= deep link opens the modal", display(page, "#comodal") == "flex")
            page.keyboard.press("Escape")
            page.wait_for_timeout(500)
            # 15: levels 1–3 and back
            page.click('.co-team a:has-text("beta")')
            page.wait_for_selector(".co-agenth", timeout=10000)
            ok("15 team name → /company/test-co/beta (Tasks)", page.url.endswith("/company/test-co/beta"), page.url)
            page.screenshot(path=f"{OUT}/company-tasks-light.png")
            tabs = page.eval_on_selector_all(".co-tabs button", "els => els.map(e => e.textContent)")
            ok("agent tabs are Tasks · Activity · Chat · Trace", tabs == ["Tasks", "Activity", "Chat", "Trace"], str(tabs))
            page.click('.co-tabs [data-level="activity"]')
            page.wait_for_timeout(5000)
            ok("15 Activity: URL /activity, the bar painted, the REAL #msgs painted, #company out of the way", page.url.endswith("/beta/activity") and display(page, "#cobar") != "none" and display(page, ".main > .msgs") != "none" and page.evaluate("getComputedStyle(document.getElementById('company')).pointerEvents") == "none", page.url)
            ok("Activity is read-only: no composer painted", display(page, ".main > .comp") == "none")
            routes = page.eval_on_selector_all(".msgs .tag.co-route", "els => els.map(e => e.textContent)")
            ok("14 Activity shows an agent↔agent row (alpha → beta) and a #test-co post", any("→ beta" in r for r in routes) and any("#test-co" in r for r in routes), str(routes[:8]))
            page.screenshot(path=f"{OUT}/company-activity-light.png")
            page.click('#cobar [data-level="chat"]')
            page.wait_for_timeout(2500)
            ok("Chat: URL /chat, operator↔agent only, the composer painted and addressed to beta", page.url.endswith("/beta/chat") and display(page, ".main > .comp") != "none" and page.get_attribute("#input", "placeholder") == "message beta" and page.locator(".msgs .tag.co-route").count() == 0, page.url)
            page.screenshot(path=f"{OUT}/company-chat-light.png")
            page.click('#cobar [data-level="trace"]')
            page.wait_for_timeout(4000)
            ok("15 Trace: the real trace body is painted", page.url.endswith("/beta/trace") and display(page, ".main > .tbody") != "none" and display(page, ".main > .msgs") == "none")
            page.screenshot(path=f"{OUT}/company-trace-light.png")
            page.go_back()
            page.wait_for_timeout(1500)
            ok("15 Back → Chat", page.url.endswith("/beta/chat"), page.url)
            page.go_back()
            page.wait_for_timeout(1500)
            ok("15 Back → Activity", page.url.endswith("/beta/activity"), page.url)
            page.go_back()
            page.wait_for_timeout(1500)
            ok("15 Back → Tasks", page.url.endswith("/company/test-co/beta") and display(page, ".co-agenth") != "missing", page.url)
            page.go_back()
            page.wait_for_timeout(1500)
            ok("15 Back → home", page.url.endswith("/company/test-co") and display(page, ".co-workhead") != "missing", page.url)
            page.goto(f"{BASE}/company/test-co/beta/dialog")
            page.wait_for_timeout(2500)
            ok("an old /dialog link lands on Activity (URL rewritten)", page.url.endswith("/beta/activity") and page.get_attribute('#cobar [data-level="activity"]', "aria-pressed") == "true", page.url)
            page.goto(f"{BASE}/company/test-co")
            page.wait_for_selector(".co-col:not(.co-loading) .co-workhead", timeout=30000)
            page.click("#cohead .co-chanlink")
            page.wait_for_timeout(2500)
            ok("header #test-co → the company channel, chromeless, composer posting to #test-co", page.url.endswith("/company/test-co/channel") and display(page, ".side") == "none" and page.get_attribute("#input", "placeholder") == "message #test-co" and "kickoff" not in page.url, page.url)
            ok("the channel view shows the kickoff", "is the Test Co company" in page.inner_text(".main > .msgs"))
            page.screenshot(path=f"{OUT}/company-channel-light.png")
            # 16 + unknown company
            page.goto(f"{BASE}/company/test-co/stranger")
            page.wait_for_timeout(2500)
            ok("16 /company/test-co/stranger → 'stranger is not in test-co'", "stranger is not in test-co" in page.inner_text("#company"))
            page.goto(f"{BASE}/company/test-co/stranger/chat")
            page.wait_for_timeout(3000)
            ok("16 …and /stranger/chat paints the 'not in' page over the shell, not a stranger's chat", "stranger is not in test-co" in page.inner_text("#company") and page.evaluate("getComputedStyle(document.getElementById('company')).pointerEvents") != "none" and display(page, "#cobar") == "none")
            page.goto(f"{BASE}/company/nope")
            page.wait_for_timeout(2500)
            ok("8 /company/nope → 'No company “nope”' + /new?name=nope", "No company" in page.inner_text("#company") and page.locator('a[href="/new?name=nope"]').count() == 1)
            # /new
            page.goto(f"{BASE}/new")
            page.wait_for_selector(".co-form", timeout=10000)
            ok("/new is chromeless too", display(page, ".side") == "none" and display(page, ".top") == "none" and "New company" in page.inner_text("#cohead"))
            tag = str(int(time.time()) % 100000)
            page.fill('[data-nf="name"]', f"UI Co {tag}")
            ok("/new derives the slug from the name", page.input_value('[data-nf="slug"]') == f"ui-co-{tag}")
            page.check('[data-pick="alpha"]')
            page.check('[data-pick="beta"]')
            page.check('[data-lead="beta"]')
            page.wait_for_timeout(200)
            ok("/new: a lead radio per picked agent; the choice sticks", page.is_checked('[data-lead="beta"]') and not page.is_checked('[data-lead="alpha"]'))
            page.screenshot(path=f"{OUT}/company-new-light.png")
            page.click('[data-act="create"]')
            page.wait_for_function("() => (document.querySelector('.co-steps')?.innerText ?? '').includes('bead filed')", timeout=60000)
            steps = page.inner_text(".co-steps")
            page.screenshot(path=f"{OUT}/company-new-steps-light.png")
            ok("/new step list: bead filed, channel, invites, kickoff", "company bead filed" in steps and "invited 2/2" in steps, steps)
            page.wait_for_url(re.compile(rf"/company/ui-co-{tag}$"), timeout=60000)
            page.wait_for_selector(".co-col:not(.co-loading) .co-workhead", timeout=30000)
            page.wait_for_timeout(2000)
            ok("Create → /company/ui-co-<n> with beta as the lead", "beta ★" in page.inner_text(".co-team"), page.inner_text(".co-team"))
            page.go_back()
            page.wait_for_timeout(1000)
            ok("Back returns to /new", page.url.endswith("/new"), page.url)
            page.goto(f"{BASE}/company/test-co")
            page.wait_for_selector(".co-col:not(.co-loading) .co-workhead", timeout=30000)
            page.wait_for_timeout(1500)
            ok("the header switcher lists the companies", page.locator("#cohead .co-switch option").count() >= 2)
            page.select_option("#cohead .co-switch", value=page.eval_on_selector("#cohead .co-switch option:not([selected])", "o => o.value"))
            page.wait_for_timeout(1500)
            ok("switching company navigates there", "/company/" in page.url and not page.url.endswith("/company/test-co"), page.url)
            page.click("#cohead .co-back")
            page.wait_for_timeout(1500)
            ok("'← paw' returns to the full shell (sidebar painted again)", display(page, ".side") != "none" and display(page, "#cohead") == "none" and not "/company/" in page.url, page.url)
            page.go_back()
            page.wait_for_timeout(1500)
            ok("Back from paw returns to the company, chromeless again", "/company/" in page.url and display(page, ".side") == "none", page.url)
        else:
            page.screenshot(path=f"{OUT}/company-home-dark.png")
            bg = page.evaluate("getComputedStyle(document.getElementById('company')).backgroundColor")
            ok("[dark] the page background is dark", bg in ("rgb(26, 29, 33)",), bg)
        ctx.close()

    # phone: no horizontal scroll, the chat collapses to a row, the panel is a full sheet
    ctx = b.new_context(viewport={"width": 390, "height": 844}, color_scheme="light", is_mobile=True, has_touch=True)
    page = ctx.new_page()
    page.goto(f"{BASE}/company/test-co")
    page.wait_for_selector(".co-col:not(.co-loading) .co-workhead", timeout=30000)
    page.wait_for_timeout(1500)
    sw = page.evaluate("Math.max(document.documentElement.scrollWidth, document.querySelector('.co-wrap').scrollWidth)")
    ok("phone: zero horizontal scroll at 390px", sw <= 390, str(sw))
    ok("phone: the lead chat collapses to a 'Chat with alpha →' row", display(page, ".co-chatslot") != "none" and "Chat with alpha" in page.inner_text(".co-chatslot"))
    ok("phone: no sidebar, no top bar; the slim header is there", display(page, ".side") == "none" and display(page, ".top") == "none" and display(page, "#cohead") == "flex")
    page.screenshot(path=f"{OUT}/company-home-phone.png")
    if page.locator(".co-work .co-bead .co-t").count() == 0:
        page.click(".co-work .co-fold")
        page.wait_for_timeout(300)
    page.click(".co-work .co-bead .co-t")
    page.wait_for_timeout(800)
    r = rect(page, ".co-modal")
    ok("phone: the bead modal is a full-screen sheet", r and abs(r["w"] - 390) < 2, str(r))
    page.screenshot(path=f"{OUT}/company-panel-phone.png")
    page.keyboard.press("Escape")
    page.click(".co-chatrow")
    page.wait_for_timeout(1000)
    ok("phone: the chat row opens the real agent chat; Back returns home", page.evaluate("location.search").startswith("?at=alpha") and display(page, ".main > .comp") != "none")
    page.go_back()
    page.wait_for_timeout(1000)
    ok("phone: Back → the company home", page.url.endswith("/company/test-co"), page.url)
    ctx.close()

    # 9: storage that THROWS — the page renders and the toggle still works
    ctx = b.new_context(viewport={"width": 1200, "height": 800})
    ctx.add_init_script("for (const k of ['getItem','setItem','removeItem']) Storage.prototype[k] = () => { throw new Error('blocked') }")
    page = ctx.new_page()
    errs = []
    page.on("pageerror", lambda e: errs.append(str(e)))
    page.goto(f"{BASE}/company/test-co")
    page.wait_for_selector(".co-col:not(.co-loading) .co-workhead", timeout=30000)
    page.click('.co-views [data-view="status"]')
    page.wait_for_timeout(300)
    ok("9 localStorage throwing → page renders and the toggle switches", page.get_attribute('.co-views [data-view="status"]', "aria-pressed") == "true" and not errs, "; ".join(errs))
    ctx.close()
    b.close()

print(f"\n{fails} browser check(s) failed" if fails else "\nall company browser checks passed")
sys.exit(1 if fails else 0)
